/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rufusrockwell (https://sketchfab.com/rufusrockwell)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/2d6ec794ac5c45939a7f23cb9d219e10
title: Blueberry
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/blueberry.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/blueberry.glb')
