/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: aidanfox (https://sketchfab.com/aidanfox)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/3e3cb1a30ad84f3db40f0d6baf613f11
title: [Low Poly] Carrot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CarrotModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/carrot.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.blinn1SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/carrot.glb')
