/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: gilles.schaeck (https://sketchfab.com/gilles.schaeck)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/maize-corn-plant-5fd3b104d8104519b061469c365d4974
title: Maize Corn Plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/corn.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.94, -3.12, 0.38]} rotation={[-Math.PI / 2, 0, -1.9]} scale={[0.79, 0.79, 0.79]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={nodes.defaultMaterial.material} />
          </group>
          <group position={[-0.73, -3.12, -0.39]} rotation={[-Math.PI / 2, 0, 2.59]} scale={[0.79, 0.79, 0.79]}>
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={nodes.defaultMaterial_1.material} />
          </group>
          <group position={[-0.47, -3.12, 1.54]} rotation={[-Math.PI / 2, 0, -2.54]} scale={[0.79, 0.79, 0.79]}>
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={nodes.defaultMaterial_2.material} />
          </group>
          <group position={[-11.9, 172.3, -3.59]} rotation={[-1.61, -0.32, -2.72]} scale={[0.27, 0.27, 0.27]}>
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={nodes.defaultMaterial_3.material} />
          </group>
          <group position={[-6.34, 154.94, -1.68]} rotation={[-1.69, -0.33, 2.59]} scale={[0.79, 0.79, 0.79]}>
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={nodes.defaultMaterial_4.material} />
          </group>
          <group position={[1.01, -3.12, -0.12]} rotation={[-Math.PI / 2, 0, 0]} scale={0.79}>
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={nodes.defaultMaterial_5.material} />
          </group>
          <group position={[-0.81, -3.12, 0.11]} rotation={[-Math.PI / 2, 0, 1.79]} scale={[0.79, 0.79, 0.79]}>
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={nodes.defaultMaterial_6.material} />
          </group>
          <group position={[12.95, 122.03, -3.31]} rotation={[-1.61, 0.33, 0]} scale={[0.27, 0.27, 0.27]}>
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={nodes.defaultMaterial_7.material} />
          </group>
          <group position={[6.85, 104.84, -1.97]} rotation={[-1.64, 0.34, 0]} scale={[0.79, 0.79, 0.79]}>
            <mesh geometry={nodes.defaultMaterial_8.geometry} material={nodes.defaultMaterial_8.material} />
          </group>
          <group position={[0.1, 265.85, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.79}>
            <mesh geometry={nodes.defaultMaterial_9.geometry} material={nodes.defaultMaterial_9.material} />
          </group>
          <group position={[-0.06, 290.1, 0.11]} rotation={[-Math.PI / 2, 0, 0.38]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_10.geometry} material={nodes.defaultMaterial_10.material} />
          </group>
          <group position={[-0.06, 290.1, 0.11]} rotation={[-Math.PI / 2, 0, 0.38]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_11.geometry} material={nodes.defaultMaterial_11.material} />
          </group>
          <group position={[0.09, 35.75, -0.12]} rotation={[-Math.PI / 2, 0, 1.44]} scale={[3.03, 3.03, 3.03]}>
            <mesh geometry={nodes.defaultMaterial_12.geometry} material={nodes.defaultMaterial_12.material} />
          </group>
          <group position={[0.09, 45.62, -0.12]} rotation={[-Math.PI / 2, 0, -3.07]} scale={[3.03, 3.03, 3.03]}>
            <mesh geometry={nodes.defaultMaterial_13.geometry} material={nodes.defaultMaterial_13.material} />
          </group>
          <group position={[0.09, 52.89, -0.12]} rotation={[-Math.PI / 2, 0, -1.6]} scale={[3.27, 3.27, 3.27]}>
            <mesh geometry={nodes.defaultMaterial_14.geometry} material={nodes.defaultMaterial_14.material} />
          </group>
          <group position={[0.09, 27.08, -0.12]} rotation={[-Math.PI / 2, 0, 0]} scale={3.03}>
            <mesh geometry={nodes.defaultMaterial_15.geometry} material={nodes.defaultMaterial_15.material} />
          </group>
          <group position={[0.09, 286.72, -0.12]} rotation={[-Math.PI / 2, 0, 2.59]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_16.geometry} material={nodes.defaultMaterial_16.material} />
          </group>
          <group position={[0.09, 286.72, -0.12]} rotation={[-Math.PI / 2, 0, 2.59]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_17.geometry} material={nodes.defaultMaterial_17.material} />
          </group>
          <group position={[0.09, 287.96, -0.12]} rotation={[-Math.PI / 2, 0, -1.13]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_18.geometry} material={nodes.defaultMaterial_18.material} />
          </group>
          <group position={[0.09, 287.96, -0.12]} rotation={[-Math.PI / 2, 0, -1.13]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_19.geometry} material={nodes.defaultMaterial_19.material} />
          </group>
          <group position={[0.09, 282.52, -0.12]} rotation={[-Math.PI / 2, 0, -1.74]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_20.geometry} material={nodes.defaultMaterial_20.material} />
          </group>
          <group position={[0.09, 282.52, -0.12]} rotation={[-Math.PI / 2, 0, -1.74]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_21.geometry} material={nodes.defaultMaterial_21.material} />
          </group>
          <group position={[0.09, 283.76, -0.12]} rotation={[-Math.PI / 2, 0, 0.82]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_22.geometry} material={nodes.defaultMaterial_22.material} />
          </group>
          <group position={[0.09, 283.76, -0.12]} rotation={[-Math.PI / 2, 0, 0.82]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_23.geometry} material={nodes.defaultMaterial_23.material} />
          </group>
          <group position={[0.09, 281.48, -0.12]} rotation={[-Math.PI / 2, 0, -0.06]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_24.geometry} material={nodes.defaultMaterial_24.material} />
          </group>
          <group position={[0.09, 281.48, -0.12]} rotation={[-Math.PI / 2, 0, -0.06]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.defaultMaterial_25.geometry} material={nodes.defaultMaterial_25.material} />
          </group>
          <group position={[0.09, 244.75, -0.12]} rotation={[-Math.PI / 2, 0, -2.4]} scale={[2.93, 2.93, 2.93]}>
            <mesh geometry={nodes.defaultMaterial_26.geometry} material={nodes.defaultMaterial_26.material} />
          </group>
          <group position={[0.09, 254.63, -0.12]} rotation={[-Math.PI / 2, 0, -0.63]} scale={[2.93, 2.93, 2.93]}>
            <mesh geometry={nodes.defaultMaterial_27.geometry} material={nodes.defaultMaterial_27.material} />
          </group>
          <group position={[0.09, 261.89, -0.12]} rotation={[-Math.PI / 2, 0, 0.84]} scale={[2.93, 2.93, 2.93]}>
            <mesh geometry={nodes.defaultMaterial_28.geometry} material={nodes.defaultMaterial_28.material} />
          </group>
          <group position={[0.09, 236.08, -0.12]} rotation={[-Math.PI / 2, 0, 2.44]} scale={[2.93, 2.93, 2.93]}>
            <mesh geometry={nodes.defaultMaterial_29.geometry} material={nodes.defaultMaterial_29.material} />
          </group>
          <group position={[0.09, 201.26, -0.12]} rotation={[-Math.PI / 2, 0, -2.4]} scale={[3.84, 3.84, 3.84]}>
            <mesh geometry={nodes.defaultMaterial_30.geometry} material={nodes.defaultMaterial_30.material} />
          </group>
          <group position={[0.09, 211.14, -0.12]} rotation={[-Math.PI / 2, 0, -0.63]} scale={[3.84, 3.84, 3.84]}>
            <mesh geometry={nodes.defaultMaterial_31.geometry} material={nodes.defaultMaterial_31.material} />
          </group>
          <group position={[0.09, 218.4, -0.12]} rotation={[-Math.PI / 2, 0, 0.84]} scale={[3.84, 3.84, 3.84]}>
            <mesh geometry={nodes.defaultMaterial_32.geometry} material={nodes.defaultMaterial_32.material} />
          </group>
          <group position={[0.09, 192.6, -0.12]} rotation={[-Math.PI / 2, 0, 2.44]} scale={[3.84, 3.84, 3.84]}>
            <mesh geometry={nodes.defaultMaterial_33.geometry} material={nodes.defaultMaterial_33.material} />
          </group>
          <group position={[0.09, 149.33, -0.12]} rotation={[-Math.PI / 2, 0, 2.92]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_34.geometry} material={nodes.defaultMaterial_34.material} />
          </group>
          <group position={[0.09, 159.21, -0.12]} rotation={[-Math.PI / 2, 0, -1.59]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_35.geometry} material={nodes.defaultMaterial_35.material} />
          </group>
          <group position={[0.09, 166.47, -0.12]} rotation={[-Math.PI / 2, 0, -0.12]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_36.geometry} material={nodes.defaultMaterial_36.material} />
          </group>
          <group position={[0.09, 140.66, -0.12]} rotation={[-Math.PI / 2, 0, 1.48]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_37.geometry} material={nodes.defaultMaterial_37.material} />
          </group>
          <group position={[0.09, 93.72, -0.12]} rotation={[-Math.PI / 2, 0, -1.09]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_38.geometry} material={nodes.defaultMaterial_38.material} />
          </group>
          <group position={[0.09, 103.59, -0.12]} rotation={[-Math.PI / 2, 0, 0.68]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_39.geometry} material={nodes.defaultMaterial_39.material} />
          </group>
          <group position={[0.09, 110.86, -0.12]} rotation={[-Math.PI / 2, 0, 2.15]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_40.geometry} material={nodes.defaultMaterial_40.material} />
          </group>
          <group position={[0.09, 85.05, -0.12]} rotation={[-Math.PI / 2, 0, -2.53]} scale={[4.07, 4.07, 4.07]}>
            <mesh geometry={nodes.defaultMaterial_41.geometry} material={nodes.defaultMaterial_41.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/corn.glb')
