/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: xenera (https://sketchfab.com/xenera)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/farm-grass-tile-e8a7f238a70a457c9394142ef3bb5533
title: farm_grass-tile
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/fancy-grass.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.grass} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.plate} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.bolt} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.wood_1} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.grass2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/fancy-grass.glb')
