/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: adam127 (https://sketchfab.com/adam127)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tropical-plant-7365d3fc0eb148028c751364dd172952
title: Tropical plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/kale.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={2.57}>
          <mesh geometry={nodes.trop_leav_4_0.geometry} material={materials.trop_leav_4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kale.glb')
