/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shio Hato (https://sketchfab.com/shiohato3)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/the-legendary-potato-by-shio-5b8fbfe171af4e3295e0bf233619a0f1
title: The Legendary Potato - By Shio
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PotatoModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/potato.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.36, 1.72, 0]}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.Potatoe} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/potato.glb')
