/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: modo20124 (https://sketchfab.com/modo20124)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/strawberry-9956de47e327480cb902877676cd63f7
title: Strawberry
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/strawberry.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 107.37, 0]} scale={1.57}>
            <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/strawberry.glb')
